scrape_configs:
  - job_name: 'Spring Boot Transaction Application'
    metrics_path: '/transaction/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: "My Spring Boot Application"